server :
  port: 2002

spring:
  application:
    name: service-a
  cloud:
    config:
      discovery :
        enabled : true    # 开启通过服务来访问Config Server的功能
        serviceId : config-server  # 指定Config Server注册的服务名
      profile : dev   # 定位git上的资源


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
    preferIpAddress: true
    hostname: service-a #版本控制的时候根据该昵称进行选择
    metadata-map:
      labelAnd: v2

config :
  name : cookie
  tel : 17311351991
  url: jdbc:mysql://114.55.127.198:82/cookie?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: root
  password: Newrank123456
  driver-class-name: com.mysql.cj.jdbc.Driver